name: Swift

on: 
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: cd ./iOS-frontend && xcodebuild test -project ./ProjectM.xcodeproj  -scheme ProjectM -configuration 'Staging'  -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' -derivedDataPath ./DerivedData