name: Swift

on: 

  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
   
